drop table department if exists;
create table department(
	id bigint generated by default as identity,
	d_name varchar(40),
	d_number int(3),
	d_part_Id varchar(20),
	d_remarks varchar(50),
	primary key(id)
);