spring:
  application:
    name: eureka-server
server:
  port: 8763
eureka:
  client:
    healthcheck:
      enabled: true
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: true
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
    #与Eureka注册服务中心的通信zone和url地址
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
---
spring:
  profiles: pro1
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: pro2
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: pro3
eureka:
  instance:
    hostname: localhost